### 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [2]:
import numpy as np

In [ ]:
def foo_1(arr,target)

In [9]:
import numpy as np

def foo_1(arr, target):
    if target not in arr:
        return 'no item found'
    
    indices = np.abs(arr - target).argmin()
    return indices

arr = np.array([1, 3, 5, 7,8,6,7,7,3,8,3,7, 9])
target = 11
res = foo_1(arr, target)

print(res)


no item found


### 3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [28]:
data=np.array([[85,89,88],[78,89,94],[91,87,90],[87,95,84]])
data

array([[85, 89, 88],
       [78, 89, 94],
       [91, 87, 90],
       [87, 95, 84]])

In [34]:

mark_score_above_90 = data[np.any(data > 90, axis=1)] # check student score 90 in any one subject

print("Scores of students with at least one score above 90:")

print(mark_score_above_90)


Scores of students with at least one score above 90:
[[78 89 94]
 [91 87 90]
 [87 95 84]]


In [35]:
def high_scoring_students(data, minimum_score=90):
    
    # Find students with at least one score above the minimum score
    high_scorers = data[np.any(data > minimum_score, axis=1)]
    return high_scorers


print("Scores of students with at least one score above", passing_score, ":")
print(high_scores)


Scores of students with at least one score above 90 :
[[78 89 94]
 [91 87 90]
 [87 95 84]]


### 3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales

In [15]:
data=np.array([[120,150,130,110],[200,180,220,250],[90,100,95,110],[300,280,320,340]])
data

array([[120, 150, 130, 110],
       [200, 180, 220, 250],
       [ 90, 100,  95, 110],
       [300, 280, 320, 340]])

In [18]:
def cal_statistics(data):
  product_stats = []
  for product in data:
    product_stats.append({
      "mean": np.mean(product),
      "median": np.median(product),
      "std": np.std(product),
      "highest_month": np.argmax(product) + 1  # Add 1 to account for 0-based indexing
    })
  return product_stats

product_stats = cal_statistics(data)

# Print the statistics for each product
print("Product Statistics:")
for i, product_stat in enumerate(product_stats):
  print(f"Product {i+1}: {product_stat}")


Product Statistics:
Product 1: {'mean': 127.5, 'median': 125.0, 'std': 14.79019945774904, 'highest_month': 2}
Product 2: {'mean': 212.5, 'median': 210.0, 'std': 25.8602010819715, 'highest_month': 4}
Product 3: {'mean': 98.75, 'median': 97.5, 'std': 7.39509972887452, 'highest_month': 4}
Product 4: {'mean': 310.0, 'median': 310.0, 'std': 22.360679774997898, 'highest_month': 4}


### 3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.



In [6]:
x=np.random.randint(1,100,1000)

counts = np.bincount(x)

top_indices = np.argsort(-counts)[:10]

print("Top 10 most frequently occurring values:")
for index in top_indices:
    print(f"Value: {index}, Count: {counts[index]}")

Top 10 most frequently occurring values:
Value: 31, Count: 18
Value: 45, Count: 16
Value: 33, Count: 16
Value: 27, Count: 16
Value: 47, Count: 15
Value: 71, Count: 15
Value: 42, Count: 15
Value: 88, Count: 15
Value: 35, Count: 14
Value: 3, Count: 14


### 2. Write a user defined function foo_2 that takes a 1 , 2,3 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.



In [7]:
def foo_2(arr, axis):
    if arr.ndim != 2:
        print("Input array must be 2-dimensional.")
    else:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts

def foo_3(arr, axis):
    if arr.ndim != 3:
        print("Input array must be 3-dimensional.")
    else:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts
    
    

arr = np.array([[1, 2, 3, 4], [0, 5, 0, 0], [2, 0, 1, 0]])
foo_2(arr, axis=0)

array([2, 2, 2, 1])

In [9]:
arr1 = np.array([[[1, 2, 3, 4], [0, 5, 0, 0], [2, 0, 1, 0]],[[2, 0, 1, 0], [0, 5, 0, 0], [1, 2, 3, 4]]])
foo_3(arr1,axis=0)


array([[2, 1, 2, 1],
       [0, 2, 0, 0],
       [2, 1, 2, 1]])

In [10]:
foo_3(arr1,axis=1)


array([[2, 2, 2, 1],
       [2, 2, 2, 1]])